# -*- coding: utf-8 -*-
"""Doc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VRRs2_Du1mtx7mLDZOMc63MpluQSQFY
"""

#Phase 1: Environment Setup & Core Architecture
#Activity 1.1: Install Dependencies & Configure Environment

pip install -U Transformers

requirements = """
gradio
transformers
torch
reportlab
requests
"""

with open("requirements.txt", "w") as f:
    f.write(requirements)

print("requirements.txt created successfully")

from google.colab import drive
drive.mount('/content/drive')

!pip install -r requirements.txt

!pip install reportlab

import reportlab
print("ReportLab installed successfully!")

import gradio
import transformers
import torch
import reportlab
import requests
import ast
import sys

print("All packages imported successfully!")
print("Python Version:", sys.version)
print("Torch Version:", torch.__version__)
print("GPU Available:", torch.cuda.is_available())

# Commented out IPython magic to ensure Python compatibility.
#Activity 1.2: Design DocGenieAnalyzer Core Class

%%writefile ast_analyzer.py
import ast

class DocGenieAnalyzer:

    def __init__(self):
        self.history = []

    def extract_functions(self, code):
        tree = ast.parse(code)
        functions = []

        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                functions.append({
                    "name": node.name,
                    "args": [arg.arg for arg in node.args.args],
                    "returns": ast.unparse(node.returns) if node.returns else None
                })

        return functions

import importlib
import ast_analyzer
importlib.reload(ast_analyzer)

# Commented out IPython magic to ensure Python compatibility.
%%writefile ast_analyzer.py
import ast

class DocGenieAnalyzer:

    def __init__(self):
        self.history = []

    def extract_functions(self, code):
        tree = ast.parse(code)
        functions = []

        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):
                functions.append({
                    "name": node.name,
                    "args": [arg.arg for arg in node.args.args],
                    "returns": ast.unparse(node.returns) if node.returns else None
                })

        return functions

    def add_history(self, function_name, docstring):
        self.history.append({
            "function": function_name,
            "docstring": docstring
        })

    def get_history(self):
        return self.history

import importlib
import ast_analyzer
importlib.reload(ast_analyzer)

from ast_analyzer import DocGenieAnalyzer

analyzer = DocGenieAnalyzer()

analyzer.add_history("add", "Adds two numbers and returns result")

print(analyzer.get_history())

# Commented out IPython magic to ensure Python compatibility.
# Activity 2.2: Build Deep Logic Analysis System


%%writefile ast_analyzer.py
import ast

class DocGenieAnalyzer:

    def __init__(self):
        self.history = []

    def extract_function_signature(self, code):
        tree = ast.parse(code)
        signatures = []

        for node in ast.walk(tree):

            if isinstance(node, ast.FunctionDef):

                parameters = []

                for arg in node.args.args:

                    param_name = arg.arg
                    param_type = ast.unparse(arg.annotation) if arg.annotation else None

                    parameters.append({
                        "name": param_name,
                        "type": param_type
                    })

                # Detect default values
                defaults = [ast.unparse(d) for d in node.args.defaults]

                # Return type
                return_type = ast.unparse(node.returns) if node.returns else None

                signatures.append({
                    "function_name": node.name,
                    "parameters": parameters,
                    "defaults": defaults,
                    "return_type": return_type
                })

        return signatures

    def add_history(self, function_name, docstring):
        self.history.append({
            "function": function_name,
            "docstring": docstring
        })

    def get_history(self):
        return self.history

import importlib
import ast_analyzer
importlib.reload(ast_analyzer)

from ast_analyzer import DocGenieAnalyzer

code = """
def calculate_total(price: float, quantity: int = 1) -> float:
    return price * quantity
"""

analyzer = DocGenieAnalyzer()

result = analyzer.extract_function_signature(code)

print(result)

# Commented out IPython magic to ensure Python compatibility.
%%writefile ast_analyzer.py
import ast

class DocGenieAnalyzer:

    def __init__(self):
        self.history = []

    # Activity 2.1
    def extract_function_signature(self, code):
        tree = ast.parse(code)
        signatures = []

        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):

                parameters = []

                for arg in node.args.args:
                    param_name = arg.arg
                    param_type = ast.unparse(arg.annotation) if arg.annotation else None

                    parameters.append({
                        "name": param_name,
                        "type": param_type
                    })

                defaults = [ast.unparse(d) for d in node.args.defaults]

                return_type = ast.unparse(node.returns) if node.returns else None

                signatures.append({
                    "function_name": node.name,
                    "parameters": parameters,
                    "defaults": defaults,
                    "return_type": return_type
                })

        return signatures


    # Activity 2.2
    def analyze_function_logic(self, code):

        tree = ast.parse(code)

        analysis = {
            "loops": [],
            "conditionals": [],
            "math_operations": [],
            "returns": [],
            "function_calls": []
        }

        for node in ast.walk(tree):

            # Detect loops
            if isinstance(node, ast.For):
                analysis["loops"].append("for loop")

            if isinstance(node, ast.While):
                analysis["loops"].append("while loop")

            # Detect conditionals
            if isinstance(node, ast.If):
                analysis["conditionals"].append("if statement")

            # Detect math operations
            if isinstance(node, ast.BinOp):

                if isinstance(node.op, ast.Add):
                    analysis["math_operations"].append("addition")

                elif isinstance(node.op, ast.Sub):
                    analysis["math_operations"].append("subtraction")

                elif isinstance(node.op, ast.Mult):
                    analysis["math_operations"].append("multiplication")

                elif isinstance(node.op, ast.Div):
                    analysis["math_operations"].append("division")

            # Detect return
            if isinstance(node, ast.Return):
                analysis["returns"].append("return statement")

            # Detect function calls
            if isinstance(node, ast.Call):
                if isinstance(node.func, ast.Name):
                    analysis["function_calls"].append(node.func.id)

        return analysis


    def add_history(self, function_name, docstring):
        self.history.append({
            "function": function_name,
            "docstring": docstring
        })

    def get_history(self):
        return self.history

import importlib
import ast_analyzer
importlib.reload(ast_analyzer)

from ast_analyzer import DocGenieAnalyzer

code = """
def process_numbers(nums):

    total = 0

    for n in nums:
        if n > 0:
            total = total + n

    return total
"""

analyzer = DocGenieAnalyzer()

result = analyzer.analyze_function_logic(code)

print(result)


#Phase 3: Interface Development & User Experience
#Activity 3.1: Build Main Code Input & Output Interface

!pip install gradio

import gradio as gr

def generate_docstring(code, style):
    result = "# Generated Docstring\n" + code
    return result

with gr.Blocks() as interface:

    gr.Markdown("# Doc-Genie Python Docstring Generator")

    code_input = gr.Code(
        label="Enter Python Code",
        language="python",
        lines=15
    )

    file_upload = gr.File(
        label="Upload Python File (.py)",
        file_types=[".py"]
    )

    docstring_style = gr.Radio(
        choices=["Google", "NumPy"],
        label="Select Docstring Style",
        value="Google"
    )

    generate_button = gr.Button("Generate Docstring")

    output_display = gr.Code(
        label="Generated Code with Docstring",
        language="python"
    )

    generate_button.click(
        fn=generate_docstring,
        inputs=[code_input, docstring_style],
        outputs=output_display
    )

interface.launch()


#Activity 3.2: Implement Export Functionality Tabs

!pip install reportlab

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
import gradio as gr
# PDF export function
def export_pdf(code):
    file_path = "docstring_output.pdf"

    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("Doc-Genie Generated Code", styles['Title']))
    elements.append(Spacer(1, 20))
    elements.append(Paragraph(code.replace("\n", "<br/>"), styles['Normal']))

    pdf = SimpleDocTemplate(file_path)
    pdf.build(elements)

    return file_path

import gradio as gr
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet


# ---------------------------
# Docstring Generator
# ---------------------------

def generate_docstring(code, style):

    if not code:
        return "No code provided."

    doc = ""

    if style == "Google":
        doc = '"""\nExample Docstring (Google Style)\n\nArgs:\n    a: first value\n    b: second value\n\nReturns:\n    result\n"""\n'
    else:
        doc = '"""\nExample Docstring (NumPy Style)\n\nParameters\n----------\na : int\nb : int\n\nReturns\n-------\nint\n"""\n'

    result = doc + code
    return result


# ---------------------------
# PDF Export
# ---------------------------

def export_pdf(code):

    file_path = "docstring_output.pdf"

    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("Doc-Genie Generated Code", styles['Title']))
    elements.append(Spacer(1,20))
    elements.append(Paragraph(code.replace("\n","<br/>"), styles['Normal']))

    pdf = SimpleDocTemplate(file_path)
    pdf.build(elements)

    return file_path


# ---------------------------
# TXT Export
# ---------------------------

def export_txt(code):

    file_path = "docstring_output.txt"

    with open(file_path,"w") as f:
        f.write(code)

    return file_path


# ---------------------------
# File Upload Reader
# ---------------------------

def load_file(file):

    if file is None:
        return ""

    with open(file.name,"r") as f:
        return f.read()


# ---------------------------
# Interface UI
# ---------------------------

with gr.Blocks() as interface:

    gr.Markdown("# Doc-Genie Python Docstring Generator")

    code_input = gr.Code(
        label="Enter Python Code",
        language="python",
        lines=15
    )

    file_upload = gr.File(
        label="Upload Python File (.py)",
        file_types=[".py"]
    )

    docstring_style = gr.Radio(
        choices=["Google","NumPy"],
        label="Select Docstring Style",
        value="Google"
    )

    generate_button = gr.Button("Generate Docstring")

    output_display = gr.Code(
        label="Generated Code with Docstring",
        language="python"
    )

    gr.Markdown("### Export Options")

    pdf_button = gr.Button("Export as PDF")
    txt_button = gr.Button("Export as TXT")

    pdf_file = gr.File(label="Download PDF")
    txt_file = gr.File(label="Download TXT")


    # Actions
    file_upload.change(
        load_file,
        inputs=file_upload,
        outputs=code_input
    )

    generate_button.click(
        generate_docstring,
        inputs=[code_input, docstring_style],
        outputs=output_display
    )

    pdf_button.click(
        export_pdf,
        inputs=output_display,
        outputs=pdf_file
    )

    txt_button.click(
        export_txt,
        inputs=output_display,
        outputs=txt_file
    )


# Launch App
interface.launch()


#Phase 4: Export & Reporting System
#Activity 4.1: Implement PDF Report Generation

import gradio as gr
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted, PageBreak
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from datetime import datetime


# PDF report function
def generate_pdf_report(code):

    file_path = "docgenie_report.pdf"

    styles = getSampleStyleSheet()
    elements = []

    # Title
    elements.append(Paragraph("Doc-Genie Documentation Report", styles['Title']))
    elements.append(Spacer(1,20))

    # Metadata
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    elements.append(Paragraph(f"Generated on: {timestamp}", styles['Normal']))
    elements.append(Spacer(1,20))

    # Code Section
    elements.append(Paragraph("Generated Code with Docstring", styles['Heading2']))
    elements.append(Spacer(1,10))

    code_block = Preformatted(code, styles['Code'])
    elements.append(code_block)

    elements.append(PageBreak())

    elements.append(Paragraph("End of Report", styles['Heading2']))

    pdf = SimpleDocTemplate(file_path, pagesize=A4)
    pdf.build(elements)

    return file_path


# Gradio Interface
with gr.Blocks() as demo:

    gr.Markdown("# Doc-Genie Report Generator")

    output_display = gr.Code(
        label="Generated Code",
        language="python"
    )

    report_button = gr.Button("Generate PDF Report")

    report_file = gr.File(label="Download Report")

    report_button.click(
        generate_pdf_report,
        inputs=output_display,
        outputs=report_file
    )


demo.launch()


#Activity 4.2: Implement Text File Export


!pip install gradio reportlab

import gradio as gr
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from datetime import datetime
import ast


# -----------------------------
# DOCSTRING GENERATOR
# -----------------------------

def generate_docstring(code, style):

    try:
        tree = ast.parse(code)
        functions = []

        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):

                func_name = node.name
                params = [arg.arg for arg in node.args.args]

                if style == "Google":
                    doc = f'"""\nFunction: {func_name}\n\nArgs:\n'
                    for p in params:
                        doc += f"    {p}: parameter\n"
                    doc += "\nReturns:\n    result\n\"\"\""

                else:
                    doc = f'"""\n{func_name} function\n\nParameters\n----------\n'
                    for p in params:
                        doc += f"{p} : type\n"
                    doc += "\nReturns\n-------\nresult\n\"\"\""

                functions.append((func_name, doc))

        for name, doc in functions:
            code = code.replace(f"def {name}", f"{doc}\ndef {name}")

        return code

    except:
        return "Error analyzing code"


# -----------------------------
# FILE UPLOAD SUPPORT
# -----------------------------

def load_file(file):

    if file is None:
        return ""

    with open(file.name, "r") as f:
        return f.read()


# -----------------------------
# PDF REPORT GENERATION
# -----------------------------

def export_pdf(code):

    file_path = "docgenie_report.pdf"
    styles = getSampleStyleSheet()

    elements = []

    elements.append(Paragraph("Doc-Genie Documentation Report", styles['Title']))
    elements.append(Spacer(1,20))

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    elements.append(Paragraph(f"Generated on: {timestamp}", styles['Normal']))
    elements.append(Spacer(1,20))

    elements.append(Paragraph("Generated Code", styles['Heading2']))
    elements.append(Spacer(1,10))

    elements.append(Preformatted(code, styles['Code']))

    pdf = SimpleDocTemplate(file_path, pagesize=A4)
    pdf.build(elements)

    return file_path


# -----------------------------
# TXT REPORT GENERATION
# -----------------------------

def export_txt(code):

    file_path = "docgenie_report.txt"

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    text = f"""
==================================
DOC-GENIE DOCUMENTATION REPORT
==================================

Generated On: {timestamp}

----------------------------------
GENERATED CODE
----------------------------------

{code}

----------------------------------
END OF REPORT
----------------------------------
"""

    with open(file_path, "w") as f:
        f.write(text)

    return file_path


# -----------------------------
# GRADIO INTERFACE
# -----------------------------

with gr.Blocks() as app:

    gr.Markdown("# 🤖 Doc-Genie Python Docstring Generator")

    file_upload = gr.File(label="Upload Python File (.py)")
    code_input = gr.Code(label="Enter Python Code", language="python")

    doc_style = gr.Radio(
        ["Google", "NumPy"],
        label="Docstring Style",
        value="Google"
    )

    generate_btn = gr.Button("Generate Docstring")

    output_code = gr.Code(label="Generated Code", language="python")

    pdf_btn = gr.Button("Export PDF Report")
    pdf_file = gr.File(label="Download PDF")

    txt_btn = gr.Button("Export TXT Report")
    txt_file = gr.File(label="Download TXT")


    file_upload.change(load_file, file_upload, code_input)

    generate_btn.click(
        generate_docstring,
        inputs=[code_input, doc_style],
        outputs=output_code
    )

    pdf_btn.click(
        export_pdf,
        inputs=output_code,
        outputs=pdf_file
    )

    txt_btn.click(
        export_txt,
        inputs=output_code,
        outputs=txt_file
    )


app.launch()

#Phase 5: Integration, Testing & Deployment
#Activity 5.1:Google Colab Deployment

import gradio as gr
import ast
from datetime import datetime
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Preformatted
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4


# -----------------------------
# FUNCTION: LOAD PYTHON FILE
# -----------------------------

def load_python_file(file):

    if file is None:
        return ""

    try:
        with open(file.name, "r") as f:
            return f.read()
    except:
        return "Error reading file"


# -----------------------------
# FUNCTION: DOCSTRING GENERATOR
# -----------------------------

def generate_docstring(code, style):

    if not code.strip():
        return "Error: Please enter Python code"

    try:
        tree = ast.parse(code)

        functions = []

        for node in ast.walk(tree):
            if isinstance(node, ast.FunctionDef):

                func_name = node.name
                params = [arg.arg for arg in node.args.args]

                # Google Style
                if style == "Google":

                    doc = f'"""\nFunction: {func_name}\n\nArgs:\n'
                    for p in params:
                        doc += f"    {p}: parameter\n"

                    doc += "\nReturns:\n    result\n\"\"\""

                # NumPy Style
                else:

                    doc = f'"""\n{func_name} function\n\nParameters\n----------\n'
                    for p in params:
                        doc += f"{p} : type\n"

                    doc += "\nReturns\n-------\nresult\n\"\"\""

                functions.append((func_name, doc))

        # Insert docstrings
        for name, doc in functions:
            code = code.replace(f"def {name}", f"{doc}\ndef {name}")

        return code

    except SyntaxError:
        return "Error: Invalid Python code. Please check syntax."

    except Exception as e:
        return f"Error occurred: {str(e)}"


# -----------------------------
# FUNCTION: PDF EXPORT
# -----------------------------

def export_pdf(code):

    if not code:
        return None

    file_path = "docgenie_report.pdf"

    styles = getSampleStyleSheet()
    elements = []

    elements.append(Paragraph("Doc-Genie Documentation Report", styles['Title']))
    elements.append(Spacer(1,20))

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    elements.append(Paragraph(f"Generated On: {timestamp}", styles['Normal']))
    elements.append(Spacer(1,20))

    elements.append(Paragraph("Generated Code", styles['Heading2']))
    elements.append(Spacer(1,10))

    elements.append(Preformatted(code, styles['Code']))

    pdf = SimpleDocTemplate(file_path, pagesize=A4)
    pdf.build(elements)

    return file_path


# -----------------------------
# FUNCTION: TXT EXPORT
# -----------------------------

def export_txt(code):

    if not code:
        return None

    file_path = "docgenie_report.txt"

    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    text = f"""
========================================
        DOC-GENIE REPORT
========================================

Generated On: {timestamp}

----------------------------------------
GENERATED CODE
----------------------------------------

{code}

----------------------------------------
END OF REPORT
----------------------------------------
"""

    with open(file_path, "w") as f:
        f.write(text)

    return file_path


# -----------------------------
# GRADIO INTERFACE
# -----------------------------

with gr.Blocks() as app:

    gr.Markdown("# 🤖 Doc-Genie AI Python Docstring Generator")

    gr.Markdown("Upload Python code or paste code to generate documentation.")

    file_upload = gr.File(label="Upload Python File (.py)")

    code_input = gr.Code(
        label="Python Code Input",
        language="python"
    )

    doc_style = gr.Radio(
        ["Google", "NumPy"],
        label="Docstring Style",
        value="Google"
    )

    generate_btn = gr.Button("Generate Docstring")

    output_code = gr.Code(
        label="Generated Code",
        language="python"
    )

    gr.Markdown("### Export Reports")

    pdf_btn = gr.Button("Export PDF")
    pdf_file = gr.File(label="Download PDF")

    txt_btn = gr.Button("Export TXT")
    txt_file = gr.File(label="Download TXT")


    # File upload → code box
    file_upload.change(
        load_python_file,
        inputs=file_upload,
        outputs=code_input
    )

    # Generate docstring
    generate_btn.click(
        generate_docstring,
        inputs=[code_input, doc_style],
        outputs=output_code
    )

    # Export PDF
    pdf_btn.click(
        export_pdf,
        inputs=output_code,
        outputs=pdf_file
    )

    # Export TXT
    txt_btn.click(
        export_txt,
        inputs=output_code,
        outputs=txt_file
    )


app.launch()

#Activity 5.2: Comprehensive Feature Testing

!pip install transformers fpdf

!pip install transformers sentencepiece fpdf gradio -q

# =====================================
# DOC-GENIE AI PYTHON DOCSTRING GENERATOR
# =====================================

import ast
import urllib.parse
import gradio as gr
from transformers import pipeline
from fpdf import FPDF

print("Loading AI Model...")

generator = pipeline(
    "text-generation",
    model="google/flan-t5-base"
)

print("Model Loaded Successfully")

# =====================================
# EXTRACT FUNCTIONS USING AST
# =====================================

def extract_functions(code):

    functions = []

    try:
        tree = ast.parse(code)

        for node in ast.walk(tree):

            if isinstance(node, ast.FunctionDef):

                func_name = node.name
                args = [arg.arg for arg in node.args.args]

                functions.append({
                    "name": func_name,
                    "args": args
                })

    except Exception as e:
        return []

    return functions


# =====================================
# GOOGLE DOCSTRING
# =====================================

def generate_google_docstring(func_name,args):

    prompt = f"""
Write a Python docstring in Google style.

Function: {func_name}
Parameters: {', '.join(args)}
"""

    try:
        result = generator(prompt,max_length=120)
        return result[0]["generated_text"]

    except:
        return "Error generating docstring"


# =====================================
# NUMPY DOCSTRING
# =====================================

def generate_numpy_docstring(func_name,args):

    prompt = f"""
Write a Python docstring in NumPy style.

Function: {func_name}
Parameters: {', '.join(args)}
"""

    try:
        result = generator(prompt,max_length=120)
        return result[0]["generated_text"]

    except:
        return "Error generating docstring"


# =====================================
# PROCESS CODE
# =====================================

def process_code(code,style):

    functions = extract_functions(code)

    if not functions:
        return "No functions detected"

    final_output = ""

    for func in functions:

        if style == "Google":

            doc = generate_google_docstring(func["name"],func["args"])

        else:

            doc = generate_numpy_docstring(func["name"],func["args"])

        final_output += f"\nFunction: {func['name']}\n"
        final_output += doc
        final_output += "\n\n-----------------------------------\n"

    return final_output


# =====================================
# PDF EXPORT
# =====================================

def export_pdf(text):

    pdf = FPDF()
    pdf.add_page()

    pdf.set_font("Arial",size=12)

    for line in text.split("\n"):

        pdf.multi_cell(0,8,line)

    file_name = "docgenie_report.pdf"
    pdf.output(file_name)

    return file_name


# =====================================
# TXT EXPORT
# =====================================

def export_txt(text):

    file_name = "docgenie_output.txt"

    with open(file_name,"w") as f:

        f.write(text)

    return file_name


# =====================================
# SHARE LINKS
# =====================================

def generate_share_link(text):

    encoded = urllib.parse.quote(text)

    twitter = f"https://twitter.com/intent/tweet?text={encoded}"

    linkedin = f"https://www.linkedin.com/sharing/share-offsite/?url={encoded}"

    return f"Twitter Share:\n{twitter}\n\nLinkedIn Share:\n{linkedin}"


# =====================================
# FILE UPLOAD HANDLER
# =====================================

def read_uploaded_file(file):

    if file is None:
        return ""

    with open(file.name,"r") as f:

        return f.read()


# =====================================
# GRADIO INTERFACE
# =====================================

with gr.Blocks(title="Doc-Genie AI") as app:

    gr.Markdown("# 🤖 Doc-Genie AI Python Docstring Generator")

    code_input = gr.Code(
        label="Enter Python Code",
        language="python",
        lines=15
    )

    file_upload = gr.File(label="Upload Python File (.py)")

    style_choice = gr.Radio(
        ["Google","NumPy"],
        value="Google",
        label="Docstring Style"
    )

    generate_btn = gr.Button("Generate Docstring")

    output_box = gr.Textbox(
        label="Generated Documentation",
        lines=20
    )

    generate_btn.click(
        process_code,
        inputs=[code_input,style_choice],
        outputs=output_box
    )

    gr.Markdown("## Export Options")

    pdf_btn = gr.Button("Export PDF")
    txt_btn = gr.Button("Export TXT")

    pdf_file = gr.File(label="Download PDF")
    txt_file = gr.File(label="Download TXT")

    pdf_btn.click(
        export_pdf,
        inputs=output_box,
        outputs=pdf_file
    )

    txt_btn.click(
        export_txt,
        inputs=output_box,
        outputs=txt_file
    )

    gr.Markdown("## Share")

    share_btn = gr.Button("Generate Share Link")

    share_output = gr.Textbox(label="Social Share Links")

    share_btn.click(
        generate_share_link,
        inputs=output_box,
        outputs=share_output
    )

